jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 
   servlet:
      context-path: /
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html

spring:
   jpa:
      hibernate:
         ddl-auto: create
   h2:
      console: true
      path: /h2-console
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:librarydb
      username: sa
      password:
      hikari:
         poolName: pool
